// <auto-generated />
using System;
using API_Edunas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Edunas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Edunas.Models.Quiz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Subject_id")
                        .HasColumnType("int");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.Property<int>("Total_questions")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Subject_id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("API_Edunas.Models.Quiz_question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("correct_option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option_a")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option_b")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option_c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option_d")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("questions_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quiz_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("quiz_id");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("API_Edunas.Models.Subjects", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("API_Edunas.Models.User_quiz_result", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("quiz_id")
                        .HasColumnType("int");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<DateTime>("submitted_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("total_correct")
                        .HasColumnType("int");

                    b.Property<int>("total_wrong")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("quiz_id");

                    b.HasIndex("user_id");

                    b.ToTable("UserQuizResults");
                });

            modelBuilder.Entity("API_Edunas.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API_Edunas.Models.Video", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Subject_id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Subject_id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("API_Edunas.Models.Quiz", b =>
                {
                    b.HasOne("API_Edunas.Models.Subjects", "Subjects")
                        .WithMany("Quiz")
                        .HasForeignKey("Subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("API_Edunas.Models.Quiz_question", b =>
                {
                    b.HasOne("API_Edunas.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("quiz_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("API_Edunas.Models.User_quiz_result", b =>
                {
                    b.HasOne("API_Edunas.Models.Quiz", "Quiz")
                        .WithMany("quiz_Results")
                        .HasForeignKey("quiz_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Edunas.Models.Users", "Users")
                        .WithMany("Quiz_Result")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("API_Edunas.Models.Video", b =>
                {
                    b.HasOne("API_Edunas.Models.Subjects", "Subjects")
                        .WithMany("Video")
                        .HasForeignKey("Subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("API_Edunas.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("quiz_Results");
                });

            modelBuilder.Entity("API_Edunas.Models.Subjects", b =>
                {
                    b.Navigation("Quiz");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("API_Edunas.Models.Users", b =>
                {
                    b.Navigation("Quiz_Result");
                });
#pragma warning restore 612, 618
        }
    }
}
